name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Allow manual triggers
  workflow_dispatch:

# Cancel previous runs when a new one begins
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

# Configure the workflow by editing these values
env:
  # The base filename of the binary produced by `cargo build`.
  cargo_build_binary_name: my_game

  # Before enabling LFS, please take a look at GitHub's documentation for costs and quota limits:
  # <https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage>
  git_lfs: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      # Required to deploy to GitHub Pages
      pages: write
      # Required for GitHub Pages to verify the source of the deployment
      id-token: write
      # Required to read repository contents
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: ${{ env.git_lfs }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: web-release
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
        env:
          # Avoid rate-limiting
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Bevy CLI
        run: cargo binstall --version 0.1.0-alpha.2 --locked --no-confirm --force --git='https://github.com/TheBevyFlock/bevy_cli' bevy_cli

      - name: Install wasm tools
        run: |
          cargo binstall --locked --no-confirm --force wasm-bindgen-cli
          cargo binstall --locked --no-confirm --force wasm-opt

      - name: Build web bundle
        run: |
          bevy build --locked --release --yes web --bundle

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/bevy_web/web-release/${{ env.cargo_build_binary_name }}/${{ env.cargo_build_binary_name }}

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
